name: Test and build Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.12.x, 1.13.x]
    steps:

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run staticcheck
      run: |
        # add executables installed with go get to PATH
        # TODO: this will hopefully be fixed by
        # https://github.com/actions/setup-go/issues/14
        export PATH=${PATH}:`go env GOPATH`/bin
        go get -u honnef.co/go/tools/cmd/staticcheck
        staticcheck ./...

    - name: Test
      run: go test -v .

    - name: Build
      run: go build -v .
